on:
  push:
    tags:
      - '*'

jobs:
  build_uboot:
    runs-on: ubuntu-latest
    name: build uboot image
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: ./build.sh
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        body_path: release-notes.txt
        files: odroid-hc4-uboot.tar.zst
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
